a="i love you girl"
print(a.upper())
print(a.lower())
print(a.replace("girl","pooja"))
print(a.split(" "))
print(a.center(50))
b=a.count("o")
print(b)
print(a.isalnum())
print(a.capitalize())